[workspace]
resolver = "3"
members = [
  "wasmtime-wasi-crypto",
  "wasmtime-host",
  "test-components/wasi-crypto-common",
  "test-components/wasi-crypto-symmetric",
  "test-components/wasi-crypto-signatures",
  "test-components/wasi-crypto-kx",
  "test-components/wasi-crypto-asymmetric-common",
]

default-members = ["wasmtime-wasi-crypto", "wasmtime-host"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.23"
wasmtime = "45.0.1"
wasmtime-wasi = "45.0.1"
wit-bindgen = "0.58.0"
