[package]
name = "wasmtime-wasi-crypto"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
wasmtime.workspace = true
wasmtime-wasi.workspace = true

anyhow.workspace = true
aes-gcm = "0.11.0"
rkyv = { version = "0.8.18", features = ["std"] }
boring = { version = "5.2.0" }
byteorder = "1.5.0"
chacha20poly1305 = "0.11.0"
derivative = "2.2.0"
ed25519-compact = { version = "2.4.0", features = ["x25519"] }
hkdf = "0.13.0"
hmac = "0.13.0"
k256 = { version = "0.14.0", features = ["ecdsa", "std", "pkcs8", "pem"] }
p256 = { version = "0.14.0", features = ["ecdsa", "std", "pkcs8", "pem"] }
p384 = { version = "0.14.0", features = ["ecdsa", "std", "pkcs8", "pem"] }
ml-kem = { version = "0.3.2", optional = true, features = ["getrandom"] }
x-wing = { version = "0.1.0-rc.0", optional = true, features = ["getrandom"] }

rand_core = "0.10.1"
getrandom = "0.4.3"
sha2 = "0.11.0"
subtle = "2.6.1"
xoodyak = "0.8.4"
zeroize = { version = "1.9.0", features = ["derive"] }

[features]
default = ["pqcrypto"]
pqcrypto = ["dep:ml-kem", "dep:x-wing"]

[badges]
maintenance = { status = "experimental" }

[lints.rust]
unused_variables = "allow"
dead_code = "allow"

[lints.clippy]
new_without_default = "allow"
new_ret_no_self = "allow"
unused_self = "allow"
wrong_self_convention = "allow"
